name: JS tests

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.6'

      - run: deno install
      - run: deno lint
        continue-on-error: true
      - run: deno task test
      - run: deno task test:node
